spring:
  config:
    import: optional:nacos:mall-product.yml
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        group: dev